title: Polars Code Academy
theme: jekyll-theme-cayman
google_analytics: G-RNRDDFWHX6

plugins:
- jekyll-remote-theme

show_downloads: false
github:
  channel_url: https://www.youtube.com/@PolarsCodeAcademy
