services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pca-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sql-scripts:/sql-scripts
      - sqlserverdata:/var/opt/mssql
    command: >
      /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30;
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P $$SA_PASSWORD -C -i /sql-scripts/init.sql; wait"
    restart: unless-stopped

volumes:
  sqlserverdata:
